// src/features/story-bible/StoryBible.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { storyBibleStore, storyBibleActions } from '../../stores/storyBibleStore';
  import type { StoryBibleProps } from '../../types/storyBible';
  
  import BraindumpEditor from './components/BraindumpEditor.svelte';
  import StyleExamplesManager from './components/StyleExamplesManager.svelte';
  import CharactersManager from './components/CharactersManager.svelte';
  import WorldbuildingManager from './components/WorldbuildingManager.svelte';
  import OutlineManager from './components/OutlineManager.svelte';
  import ScenesManager from './components/ScenesManager.svelte';
  import LoadingSpinner from '../../components/ui/LoadingSpinner.svelte';
  import ErrorMessage from '../../components/ui/ErrorMessage.svelte';
  
  export let projectId: string;
  export let seriesId: string | undefined = undefined;
  
  $: state = $storyBibleStore;
  
  const tabs = [
    { id: 'braindump', label: 'Braindump', icon: '📝' },
    { id: 'style-examples', label: 'Style Examples', icon: '✍️' },
    { id: 'characters', label: 'Characters', icon: '👥' },
    { id: 'worldbuilding', label: 'World Building', icon: '🌍' },
    { id: 'outline', label: 'Outline', icon: '📋' },
    { id: 'scenes', label: 'Scenes', icon: '🎬' }
  ] as const;
  
  onMount(async () => {
    // Load the story bible for this project
    await storyBibleActions.loadStoryBible(projectId);
    
    // Load world elements for the project
    await storyBibleActions.loadWorldElements(projectId);
    
    // Load outlines for the project
    await storyBibleActions.loadOutlines(projectId);
  });
  
  function handleTabClick(tabId: typeof state.activeTab) {
    storyBibleActions.setActiveTab(tabId);
  }
  
  function clearErrors() {
    storyBibleActions.clearAllErrors();
  }
</script>

<div class="story-bible-container">
  <!-- Header -->
  <div class="story-bible-header">
    <h1 class="title">
      <span class="icon">📚</span>
      Story Bible
    </h1>
    
    {#if state.error}
      <ErrorMessage 
        message={state.error} 
        onDismiss={clearErrors}
        type="error"
      />
    {/if}
  </div>
  
  <!-- Tab Navigation -->
  <div class="tab-navigation">
    {#each tabs as tab}
      <button 
        class="tab-button" 
        class:active={state.activeTab === tab.id}
        on:click={() => handleTabClick(tab.id)}
        disabled={state.isLoading}
      >
        <span class="tab-icon">{tab.icon}</span>
        <span class="tab-label">{tab.label}</span>
      </button>
    {/each}
  </div>
  
  <!-- Content Area -->
  <div class="content-area">
    {#if state.isLoading}
      <div class="loading-container">
        <LoadingSpinner size="large" />
        <p>Loading Story Bible...</p>
      </div>
    {:else}
      <!-- Braindump Tab -->
      {#if state.activeTab === 'braindump'}
        <BraindumpEditor 
          {projectId}
          content={state.storyBible?.braindump || ''}
          synopsis={state.storyBible?.synopsis || ''}
          genre={state.storyBible?.genre || ''}
          style={state.storyBible?.style || ''}
          styleExamples={state.storyBible?.style_examples || ''}
          povMode={state.storyBible?.pov_mode || ''}
          globalPov={state.storyBible?.global_pov || ''}
          globalTense={state.storyBible?.global_tense || ''}
          globalCharacterPovIds={state.storyBible?.global_character_pov_ids || ''}
        />
      {/if}
      
      <!-- Style Examples Tab -->
      {#if state.activeTab === 'style-examples'}
        <StyleExamplesManager 
          {projectId}
        />
      {/if}
      
      <!-- Characters Tab -->
      {#if state.activeTab === 'characters'}
        <CharactersManager 
          {projectId}
          {seriesId}
          characterId={state.selectedCharacterId}
        />
      {/if}
      
      <!-- World Building Tab -->
      {#if state.activeTab === 'worldbuilding'}
        <WorldbuildingManager 
          {projectId}
          {seriesId}
        />
      {/if}
      
      <!-- Outline Tab -->
      {#if state.activeTab === 'outline'}
        <OutlineManager 
          {projectId}
        />
      {/if}
      
      <!-- Scenes Tab -->
      {#if state.activeTab === 'scenes'}
        <ScenesManager 
          outlineId={state.selectedOutlineId || ''}
        />
      {/if}
    {/if}
  </div>
</div>

<style>
  .story-bible-container {
    display: flex;
    flex-direction: column;
    height: 100%;
    background: var(--bg-primary);
    color: var(--text-primary);
  }
  
  .story-bible-header {
    padding: 1.5rem 2rem;
    border-bottom: 1px solid var(--border-color);
    background: var(--bg-secondary);
  }
  
  .title {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    margin: 0;
    font-size: 1.75rem;
    font-weight: 600;
    color: var(--text-primary);
  }
  
  .icon {
    font-size: 2rem;
  }
  
  .tab-navigation {
    display: flex;
    background: var(--bg-secondary);
    border-bottom: 1px solid var(--border-color);
    overflow-x: auto;
  }
  
  .tab-button {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 1rem 1.5rem;
    background: none;
    border: none;
    color: var(--text-secondary);
    cursor: pointer;
    transition: all 0.2s ease;
    white-space: nowrap;
    border-bottom: 3px solid transparent;
  }
  
  .tab-button:hover {
    background: var(--bg-hover);
    color: var(--text-primary);
  }
  
  .tab-button.active {
    color: var(--accent-primary);
    border-bottom-color: var(--accent-primary);
    background: var(--bg-primary);
  }
  
  .tab-button:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  
  .tab-icon {
    font-size: 1.2rem;
  }
  
  .tab-label {
    font-weight: 500;
  }
  
  .content-area {
    flex: 1;
    overflow: hidden;
    display: flex;
    flex-direction: column;
  }
  
  .loading-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    flex: 1;
    gap: 1rem;
    color: var(--text-secondary);
  }
  
  /* Responsive Design */
  @media (max-width: 768px) {
    .story-bible-header {
      padding: 1rem;
    }
    
    .title {
      font-size: 1.5rem;
    }
    
    .tab-button {
      padding: 0.75rem 1rem;
    }
    
    .tab-label {
      display: none;
    }
    
    .tab-icon {
      font-size: 1.5rem;
    }
  }
  
  /* Dark mode support */
  @media (prefers-color-scheme: dark) {
    .story-bible-container {
      --bg-primary: #1a1a1a;
      --bg-secondary: #2d2d2d;
      --bg-hover: #3d3d3d;
      --text-primary: #ffffff;
      --text-secondary: #b3b3b3;
      --border-color: #404040;
      --accent-primary: #4f9eff;
    }
  }
  
  /* Light mode support */
  @media (prefers-color-scheme: light) {
    .story-bible-container {
      --bg-primary: #ffffff;
      --bg-secondary: #f8f9fa;
      --bg-hover: #e9ecef;
      --text-primary: #212529;
      --text-secondary: #6c757d;
      --border-color: #dee2e6;
      --accent-primary: #0066cc;
    }
  }
</style>

// src/features/story-bible/components/react/StoryBible.tsx
import React, { useState, useEffect } from 'react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../../../../components/ui/tabs';
import { Card, CardContent, CardHeader, CardTitle } from '../../../../components/ui/Card';
import { Button } from '../../../../components/ui/Button';
import BraindumpEditor from './BraindumpEditor';
import StyleExamplesManager from './StyleExamplesManager';
import CharactersManager from './CharactersManager';
import WorldbuildingManager from './WorldbuildingManager';
import OutlineManager from './OutlineManager';
import ScenesManager from './ScenesManager';
import { useStoryBible } from '../../hooks/useStoryBible';
import type { StoryBibleProps } from '../../../../types/storyBible';

export const StoryBible: React.FC<StoryBibleProps> = ({ projectId, seriesId }) => {
  const [activeTab, setActiveTab] = useState<'braindump' | 'characters' | 'worldbuilding' | 'outline' | 'scenes'>('braindump');
  const { storyBible, isLoading, error, loadStoryBible, clearError } = useStoryBible();

  useEffect(() => {
    if (projectId) {
      loadStoryBible(projectId);
    }
  }, [projectId, loadStoryBible]);

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
        <span className="ml-2 text-slate-600">Loading Story Bible...</span>
      </div>
    );
  }

  if (error) {
    return (
      <Card className="m-4">
        <CardContent className="p-6">
          <div className="text-red-600 mb-4">
            <h3 className="font-semibold mb-2">Error Loading Story Bible</h3>
            <p>{error}</p>
          </div>
          <Button onClick={clearError} variant="outline">
            Dismiss
          </Button>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="story-bible h-full flex flex-col bg-slate-50 dark:bg-slate-900">
      {/* Header */}
      <div className="border-b border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 px-6 py-4">
        <div className="flex justify-between items-start">
          <div>
            <h1 className="text-2xl font-bold text-slate-900 dark:text-slate-100 mb-1">
              Story Bible
            </h1>
            <p className="text-slate-600 dark:text-slate-400 text-sm">
              Manage your story's world, characters, and narrative structure
            </p>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" size="sm">
              Export
            </Button>
            <Button variant="outline" size="sm">
              Import
            </Button>
          </div>
        </div>
      </div>

      {/* Tabs Navigation */}
      <Tabs value={activeTab} onValueChange={(value) => setActiveTab(value as any)} className="flex-1 flex flex-col">
        <div className="border-b border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 px-6">
          <TabsList className="grid w-full grid-cols-6">
            <TabsTrigger value="braindump" className="flex items-center gap-2">
              <span>🧠</span>
              Braindump
            </TabsTrigger>
            <TabsTrigger value="style-examples" className="flex items-center gap-2">
              <span>✍️</span>
              Style Examples
            </TabsTrigger>
            <TabsTrigger value="characters" className="flex items-center gap-2">
              <span>👥</span>
              Characters
            </TabsTrigger>
            <TabsTrigger value="worldbuilding" className="flex items-center gap-2">
              <span>🌍</span>
              Worldbuilding
            </TabsTrigger>
            <TabsTrigger value="outline" className="flex items-center gap-2">
              <span>📋</span>
              Outline
            </TabsTrigger>
            <TabsTrigger value="scenes" className="flex items-center gap-2">
              <span>🎬</span>
              Scenes
            </TabsTrigger>
          </TabsList>
        </div>

        {/* Tab Content */}
        <div className="flex-1 overflow-hidden">
          <TabsContent value="braindump" className="h-full m-0">
            <BraindumpEditor projectId={projectId} />
          </TabsContent>
          
          <TabsContent value="style-examples" className="h-full m-0">
            <StyleExamplesManager projectId={projectId} />
          </TabsContent>
          
          <TabsContent value="characters" className="h-full m-0">
            <CharactersManager projectId={projectId} seriesId={seriesId} />
          </TabsContent>
          
          <TabsContent value="worldbuilding" className="h-full m-0">
            <WorldbuildingManager projectId={projectId} seriesId={seriesId} />
          </TabsContent>
          
          <TabsContent value="outline" className="h-full m-0">
            <OutlineManager projectId={projectId} />
          </TabsContent>
          
          <TabsContent value="scenes" className="h-full m-0">
            <ScenesManager outlineId="" />
          </TabsContent>
        </div>
      </Tabs>
    </div>
  );
};

export default StoryBible;
