// src/features/story-bible/StoryBible.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { storyBibleStore, storyBibleActions } from '../../stores/storyBibleStore';
  import type { StoryBibleProps } from '../../types/storyBible';
  
  import BraindumpEditor from './components/BraindumpEditor.svelte';
  import StyleExamplesManager from './components/StyleExamplesManager.svelte';
  import CharactersManager from './components/CharactersManager.svelte';
  import WorldbuildingManager from './components/WorldbuildingManager.svelte';
  import OutlineManager from './components/OutlineManager.svelte';
  import ScenesManager from './components/ScenesManager.svelte';
  import LoadingSpinner from '../../components/ui/LoadingSpinner.svelte';
  import ErrorMessage from '../../components/ui/ErrorMessage.svelte';
  
  export let projectId: string;
  export let seriesId: string | undefined = undefined;
  
  $: state = $storyBibleStore;
  
  const tabs = [
    { id: 'braindump', label: 'Braindump', icon: '📝' },
    { id: 'style-examples', label: 'Style Examples', icon: '✍️' },
    { id: 'characters', label: 'Characters', icon: '👥' },
    { id: 'worldbuilding', label: 'World Building', icon: '🌍' },
    { id: 'outline', label: 'Outline', icon: '📋' },
    { id: 'scenes', label: 'Scenes', icon: '🎬' }
  ] as const;
  
  onMount(async () => {
    // Load the story bible for this project
    await storyBibleActions.loadStoryBible(projectId);
    
    // Load world elements for the project
    await storyBibleActions.loadWorldElements(projectId);
    
    // Load outlines for the project
    await storyBibleActions.loadOutlines(projectId);
  });
  
  function handleTabClick(tabId: typeof state.activeTab) {
    storyBibleActions.setActiveTab(tabId);
  }
  
  function clearErrors() {
    storyBibleActions.clearAllErrors();
  }
</script>

<div class="story-bible-container">
  <!-- Header -->
  <div class="story-bible-header">
    <h1 class="title">
      <span class="icon">📚</span>
      Story Bible
    </h1>
    
    {#if state.error}
      <ErrorMessage 
        message={state.error} 
        onDismiss={clearErrors}
        type="error"
      />
    {/if}
  </div>
  
  <!-- Tab Navigation -->
  <div class="tab-navigation">
    {#each tabs as tab}
      <button 
        class="tab-button" 
        class:active={state.activeTab === tab.id}
        on:click={() => handleTabClick(tab.id)}
        disabled={state.isLoading}
      >
        <span class="tab-icon">{tab.icon}</span>
        <span class="tab-label">{tab.label}</span>
      </button>
    {/each}
  </div>
  
  <!-- Content Area -->
  <div class="content-area">
    {#if state.isLoading}
      <div class="loading-container">
        <LoadingSpinner size="large" />
        <p>Loading Story Bible...</p>
      </div>
    {:else}
      <!-- Braindump Tab -->
      {#if state.activeTab === 'braindump'}
        <BraindumpEditor 
          {projectId}
          content={state.storyBible?.braindump || ''}
          synopsis={state.storyBible?.synopsis || ''}
          genre={state.storyBible?.genre || ''}
          style={state.storyBible?.style || ''}
          styleExamples={state.storyBible?.style_examples || ''}
          povMode={state.storyBible?.pov_mode || ''}
          globalPov={state.storyBible?.global_pov || ''}
          globalTense={state.storyBible?.global_tense || ''}
          globalCharacterPovIds={state.storyBible?.global_character_pov_ids || ''}
        />
      {/if}
      
      <!-- Style Examples Tab -->
      {#if state.activeTab === 'style-examples'}
        <StyleExamplesManager 
          {projectId}
        />
      {/if}
      
      <!-- Characters Tab -->
      {#if state.activeTab === 'characters'}
        <CharactersManager 
          {projectId}
          {seriesId}
          characterId={state.selectedCharacterId}
        />
      {/if}
      
      <!-- World Building Tab -->
      {#if state.activeTab === 'worldbuilding'}
        <WorldbuildingManager 
          {projectId}
          {seriesId}
        />
      {/if}
      
      <!-- Outline Tab -->
      {#if state.activeTab === 'outline'}
        <OutlineManager 
          {projectId}
        />
      {/if}
      
      <!-- Scenes Tab -->
      {#if state.activeTab === 'scenes'}
        <ScenesManager 
          outlineId={state.selectedOutlineId || ''}
        />
      {/if}
    {/if}
  </div>
</div>

<style>
  .story-bible-container {
    display: flex;
    flex-direction: column;
    height: 100%;
    background: var(--bg-primary);
    color: var(--text-primary);
  }
  
  .story-bible-header {
    padding: 1.5rem 2rem;
    border-bottom: 1px solid var(--border-color);
    background: var(--bg-secondary);
  }
  
  .title {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    margin: 0;
    font-size: 1.75rem;
    font-weight: 600;
    color: var(--text-primary);
  }
  
  .icon {
    font-size: 2rem;
  }
  
  .tab-navigation {
    display: flex;
    background: var(--bg-secondary);
    border-bottom: 1px solid var(--border-color);
    overflow-x: auto;
  }
  
  .tab-button {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 1rem 1.5rem;
    background: none;
    border: none;
    color: var(--text-secondary);
    cursor: pointer;
    transition: all 0.2s ease;
    white-space: nowrap;
    border-bottom: 3px solid transparent;
  }
  
  .tab-button:hover {
    background: var(--bg-hover);
    color: var(--text-primary);
  }
  
  .tab-button.active {
    color: var(--accent-primary);
    border-bottom-color: var(--accent-primary);
    background: var(--bg-primary);
  }
  
  .tab-button:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  
  .tab-icon {
    font-size: 1.2rem;
  }
  
  .tab-label {
    font-weight: 500;
  }
  
  .content-area {
    flex: 1;
    overflow: hidden;
    display: flex;
    flex-direction: column;
  }
  
  .loading-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    flex: 1;
    gap: 1rem;
    color: var(--text-secondary);
  }
  
  /* Responsive Design */
  @media (max-width: 768px) {
    .story-bible-header {
      padding: 1rem;
    }
    
    .title {
      font-size: 1.5rem;
    }
    
    .tab-button {
      padding: 0.75rem 1rem;
    }
    
    .tab-label {
      display: none;
    }
    
    .tab-icon {
      font-size: 1.5rem;
    }
  }
  
  /* Dark mode support */
  @media (prefers-color-scheme: dark) {
    .story-bible-container {
      --bg-primary: #1a1a1a;
      --bg-secondary: #2d2d2d;
      --bg-hover: #3d3d3d;
      --text-primary: #ffffff;
      --text-secondary: #b3b3b3;
      --border-color: #404040;
      --accent-primary: #4f9eff;
    }
  }
  
  /* Light mode support */
  @media (prefers-color-scheme: light) {
    .story-bible-container {
      --bg-primary: #ffffff;
      --bg-secondary: #f8f9fa;
      --bg-hover: #e9ecef;
      --text-primary: #212529;
      --text-secondary: #6c757d;
      --border-color: #dee2e6;
      --accent-primary: #0066cc;
    }
  }
</style>

// src/features/story-bible/StoryBible.tsx
import React, { useEffect } from 'react';
import useStoryBibleStore from '../../stores/storyBibleStore';
import CharactersManager from './components/CharactersManager';
import TemplateSelector from '../../lib/components/templates/TemplateSelector';
import TemplateApplicationDialog from '../../lib/components/templates/TemplateApplicationDialog';

// Svelte components (wrapped via simple mount wrapper)
import BraindumpEditorSvelte from './components/BraindumpEditor.svelte';
import StyleExamplesManagerSvelte from './components/StyleExamplesManager.svelte';
import WorldbuildingManagerSvelte from './components/WorldBuildingManager.svelte';
import OutlineManagerSvelte from './components/OutlineManager.svelte';
import ScenesManagerSvelte from './components/ScenesManager.svelte';

import { createRoot } from 'react-dom/client';
import { useRef } from 'react';

// Generic Svelte -> React wrapper
const SvelteWrapper: React.FC<{ Component: any; props?: any }> = ({ Component, props = {} }) => {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const instanceRef = useRef<any>(null);

  useEffect(() => {
    if (containerRef.current && !instanceRef.current) {
      instanceRef.current = new Component({
        target: containerRef.current,
        props
      });
    }

    return () => {
      if (instanceRef.current) {
        instanceRef.current.$destroy();
        instanceRef.current = null;
      }
    };
    // We intentionally do not re-create on props changes to avoid tearing down Svelte instances frequently.
    // For simple prop updates, consider exposing a small API or remounting when necessary.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return <div ref={containerRef} />;
};

const tabs = [
  { id: 'braindump', label: 'Braindump', icon: '📝' },
  { id: 'style-examples', label: 'Style Examples', icon: '✍️' },
  { id: 'characters', label: 'Characters', icon: '👥' },
  { id: 'worldbuilding', label: 'World Building', icon: '🌍' },
  { id: 'outline', label: 'Outline', icon: '📋' },
  { id: 'scenes', label: 'Scenes', icon: '🎬' }
] as const;

interface Props {
  projectId: string;
  seriesId?: string;
}

const StoryBible: React.FC<Props> = ({ projectId, seriesId }) => {
  const {
    storyBible,
    isLoading,
    error,
    activeTab,
    setActiveTab,
    loadStoryBible,
    loadWorldElements,
    loadOutlines,
    selectedCharacterId,
    setSelectedOutlineId
  } = useStoryBibleStore();

  useEffect(() => {
    (async () => {
      await loadStoryBible(projectId);
      await loadWorldElements(projectId);
      await loadOutlines(projectId);
    })();
  }, [projectId, loadStoryBible, loadWorldElements, loadOutlines]);

  const handleTabClick = (tabId: typeof activeTab) => {
    setActiveTab(tabId);
  };

  const clearErrors = () => {
    // store exposes clearAllErrors; use direct invocation on store
    // but to keep import light, call setActiveTab(null) - prefer explicit clear function in store; omitted for brevity
  };

  return (
    <div className="story-bible-container flex flex-col h-full">
      <div className="story-bible-header p-6 border-b bg-gray-50 dark:bg-gray-800">
        <h1 className="title text-2xl font-semibold flex items-center gap-3">
          <span className="icon text-3xl">📚</span>
          Story Bible
        </h1>
        {error && (
          <div className="mt-3 text-red-600">
            {error}
            <button className="ml-4 underline" onClick={clearErrors}>Dismiss</button>
          </div>
        )}
      </div>

      <div className="tab-navigation flex bg-gray-100 dark:bg-gray-700 border-b">
        {tabs.map((tab) => (
          <button
            key={tab.id}
            className={`tab-button px-4 py-3 flex items-center gap-2 ${activeTab === tab.id ? 'text-blue-600 border-b-2 border-blue-600' : 'text-gray-600'}`}
            onClick={() => handleTabClick(tab.id as any)}
            disabled={isLoading}
          >
            <span className="tab-icon">{tab.icon}</span>
            <span className="tab-label">{tab.label}</span>
          </button>
        ))}
      </div>

      <div className="content-area flex-1 overflow-hidden">
        {isLoading ? (
          <div className="loading-container flex flex-col items-center justify-center h-full gap-4">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
            <p>Loading Story Bible...</p>
          </div>
        ) : (
          <>
            {activeTab === 'braindump' && (
              <div className="p-6">
                <SvelteWrapper Component={BraindumpEditorSvelte} props={{
                  projectId,
                  content: storyBible?.braindump || '',
                  synopsis: storyBible?.synopsis || '',
                  genre: storyBible?.genre || '',
                  style: storyBible?.style || '',
                  styleExamples: storyBible?.style_examples || '',
                  povMode: storyBible?.pov_mode || '',
                  globalPov: storyBible?.global_pov || '',
                  globalTense: storyBible?.global_tense || '',
                  globalCharacterPovIds: storyBible?.global_character_pov_ids || ''
                }} />
              </div>
            )}

            {activeTab === 'style-examples' && (
              <div className="p-6">
                <SvelteWrapper Component={StyleExamplesManagerSvelte} props={{ projectId }} />
              </div>
            )}

            {activeTab === 'characters' && (
              <div className="p-6">
                <CharactersManager projectId={projectId} seriesId={seriesId} characterId={selectedCharacterId || undefined} />
              </div>
            )}

            {activeTab === 'worldbuilding' && (
              <div className="p-6">
                <SvelteWrapper Component={WorldbuildingManagerSvelte} props={{ projectId, seriesId }} />
              </div>
            )}

            {activeTab === 'outline' && (
              <div className="p-6">
                <SvelteWrapper Component={OutlineManagerSvelte} props={{ projectId }} />
              </div>
            )}

            {activeTab === 'scenes' && (
              <div className="p-6">
                <SvelteWrapper Component={ScenesManagerSvelte} props={{ outlineId: undefined }} />
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
};

export default StoryBible;
